---
- hosts: localhost
  gather_facts: no
  vars:
    ami_id: ami-022e1a32d3f742bd8
  module_defaults:
    group/aws:
      region: us-east-1
  tasks:
    - name: Provision Bobs EC2 instance
      amazon.aws.ec2_instance: 
        key_name: 4970
        security_group: Module5-developer-sg
        instance_type: t3.nano
        image_id: "{{ ami_id }}"
        tags:
          Name: Module5 Bob
          Module: 5
          Department: Accounting
        wait: yes
        vpc_subnet_id: "{{ public_subnet.subnet.id }}"
        network:
          assign_public_ip: yes
        exact_count: 1
        filters:
          tag:Name: Module5 Bob
    - name: Provision Marys EC2 instance
      amazon.aws.ec2_instance: 
        key_name: 4970
        security_group: Module5-developer-sg
        instance_type: t3.nano
        image_id: "{{ ami_id }}"
        tags:
          Name: Module5 Mary
          Module: 5
          Department: Accounting
        wait: yes
        vpc_subnet_id: "{{ public_subnet.subnet.id }}"
        network:
          assign_public_ip: yes
        exact_count: 1
        filters:
          tag:Name: Module5 Mary
    - name: Provision Sally EC2 instance
      amazon.aws.ec2_instance: 
        key_name: 4970
        security_group: Module5-developer-sg
        instance_type: t3.nano
        image_id: "{{ ami_id }}"
        tags:
          Name: Module5 Sally
          Module: 5
          Department: DevOps
        wait: yes
        vpc_subnet_id: "{{ public_subnet.subnet.id }}"
        network:
          assign_public_ip: yes
        exact_count: 1
        filters:
          tag:Name: Module5 Sally
          
